import type { ProductDescription } from "@/hooks/api/useGetProductDescriptions";

/**
 * Product descriptions loaded from product-integrations.json (generated at build time)
 * or falling back to an empty list if no integrations are built.
 *
 * The product-integrations.json file is generated by scripts/generate-integrations-json.js
 * from each product's product-manifest.json after their UI builds are copied to public/ui/.
 */

interface ProductManifest {
  shortname: string;
  title: Record<string, string>;
  description: Record<string, string>;
  icon: string | null;
  docs: string | null;
  component: { type: "component" | "markdown" | "link"; ref: string };
  preview?: string;
  hasRemoteEntry?: boolean;
}

interface ProductIntegrationsJson {
  products: ProductManifest[];
  buildTime: string;
}

let _cached: ProductIntegrationsJson | null = null;

async function loadProductIntegrations(): Promise<ProductIntegrationsJson> {
  if (_cached) return _cached;
  try {
    const res = await fetch("/product-integrations.json");
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    _cached = await res.json();
    return _cached!;
  } catch {
    console.warn(
      "[mock] No product-integrations.json found, using empty product list",
    );
    _cached = { products: [], buildTime: new Date().toISOString() };
    return _cached;
  }
}

function manifestToDescriptions(
  manifest: ProductManifest,
  language: string,
): ProductDescription {
  return {
    shortname: manifest.shortname,
    title:
      manifest.title[language] || manifest.title["en"] || manifest.shortname,
    icon: manifest.icon,
    description:
      manifest.description[language] || manifest.description["en"] || "",
    language,
    docs: manifest.docs,
    component: manifest.component,
  };
}

export async function getMockProducts(
  language: string,
): Promise<ProductDescription[]> {
  const data = await loadProductIntegrations();
  return data.products.map((p) => manifestToDescriptions(p, language));
}

// Synchronous fallback for backward compat — returns empty until loaded
export const mockProducts: Record<string, ProductDescription[]> = new Proxy(
  {} as Record<string, ProductDescription[]>,
  {
    get() {
      // Return empty array; the async getMockProducts() should be used instead
      return [];
    },
  },
);

export const mockAdminProducts = mockProducts;
