on:
  pull_request:

jobs:
  versiontag:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5
      - name: Check version tag
        run: |
          curl -f https://raw.githubusercontent.com/pvarki/react-rasenmaeher-ui-v2//main/package.json -o /tmp/main_package.json || touch /tmp/main_package.json
          grep '"version":' package.json >/tmp/version.txt
          grep '"version":' /tmp/main_package.json >/tmp/main_version.txt
          diff /tmp/main_version.txt /tmp/version.txt && exit 1 || exit 0

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run prettier
        run: pnpm run format:check

      - name: Run secretlint
        run: pnpm run lint:secrets

    # TODO: add unit tests
